### ISSUE TITLE
ffmpeg & mpv missing?

### ISSUE THREAD

**Issue by Pytheas54** [ayufan-rock64/linux-build#147]
Trying out Stretch Minimal (0.6.28)
Cannot simply install any desktop as ffmpeg & mpv have unmet dependencies.
Wasn't the problem solved since 0.6.25 ?

**Comment by ayufan** [comment]
It works only on bionic

**Comment by evilbunny2008** [comment]
If you want debian mate, try this image....

http://files.pine64.org/os/ROCK64/debian/stretch-mate-rock64-0.5.15-136-20171222-arm64.img.xz

**Comment by ayufan** [comment]
The `mpv` and `ffmpeg` are not supported on `stretch`, only `bionic` currently.

**Comment by hyptechdev2015** [comment]
alternative using compiled executable of ffmpeg
[https://johnvansickle.com/ffmpeg/](https://johnvansickle.com/ffmpeg/)

**Comment by ayufan** [comment]
I doubt that it contains rkmpp enabled, which makes it useless on rock.

**Comment by L3rchal** [comment]
Still thought it would be great to have ffmpeg on debian minimal stretch

**Comment by rockford** [comment]
Hm, on my debian stretch install it works. But can't remember what exactly I did to get it to work. Should be in the irc logs somewhere.

**Comment by rockford** [comment]
I used longchairs mpv and:

ffmpeg version N-90100-g7dc8752e61 Copyright (c) 2000-2018 the FFmpeg developers
  built with gcc 6.3.0 (Debian 6.3.0-18) 20170516
  configuration: --enable-rkmpp --enable-version3 --enable-libdrm

sadly I can't remember where I got this from.

**Comment by didi1357** [comment]
ffmpeg installation seems to be broken now on bionic too, as Ubuntu Upstream released dependencies on newer versions of packets which are implemented/modified by @ayufan 

Steps to reproduce:
1.) Set up Ubuntu Bionic on Rock64
2.) added ayufan's ppa
3.) apt install ffmpeg
`ffmpeg : Depends: libavdevice58 (>= 7:3.5~git20180113) but it is not going to be installed`
4.) Tracking down the root cause by trying to install libavdevice58 with apt leads to other packets showing the same error until trying to install libgl1-mesa-dri:
`libgl1-mesa-dri :
Depends: libdrm-amdgpu1 (>= 2.4.90) but 2.4.89-1ayufan1 is to be installed
Depends: libdrm-freedreno1 (>= 2.4.92) but 2.4.89-1ayufan1 is to be installed
`

**Comment by dowoco** [comment]
@ayufan 
I have the same ffmpeg experience using "bionic-minimal-rock64-0.7.12-1077-arm64". Would it be possible to get the dependencies updated?
