### ISSUE TITLE
Why limited to 1.8ghz? 

### ISSUE THREAD

**Issue by Zelex** [ayufan-rock64/linux-build#305]
The rk3399 can be clocked all the way up to 2ghz with proper cooling. Why is the rock pro 64 limited?

**Comment by dukla2000** [comment]
This is all part of the conspiracy against people who write before they read :-)

The RK3399 [specification as per the datasheet ](http://wiki.pine64.org/index.php/ROCKPro64_Main_Page#Datasheets_for_Components_and_Peripherals) is 1.8/1.4. And since several releases back Ayufan has been focussed on stability

> 0.7.6: Change OPP's for Rock64 and RockPro64

The RK3399**K** is specified to 2.0/1.6.

Cooling is only an issue to prevent thermal throttling: my RockPro64 overclocks to 2.1/1.5 just fine though.

**Comment by Zelex** [comment]
Gotcha, thanks!
