### ISSUE TITLE
Buster with kernel 5.1 or newer doesn't support USB Storage

### ISSUE THREAD

**Issue by jedwabny** [ayufan-rock64/linux-build#391]
Hi,

There appeared the problem with disk connected through USB-to-SATA adapter (JMicron from Pine Store) using the latest kernel images. 

The last know working is 5.0.0-1105. There are a few newer and confirmed as being not working: 5.1.0-1114, 5.2.0-1116, 5.3.0-rc4-1118. The other weren't tested.

Steps:
1) Install Buster Minimal 0.9.8 for Rock64 on sd card and boot it
2) Upgrade kernel to affected one
3) Reboot system with the new kernel
3) Connect the disk with SATA adapter to USB3.

Current results:
LED on adapter should be green/red but is completely off
Disk is not visible in system even nothing in dmesg
Since these kernel versions, there is as could be expected, also no way to boot system completely installed on USB Storage

**Comment by zethexx** [comment]
For me my USB3 to SATA cable (connected to mechanical HDD) worked. I just couldn't use USB flash drives, tried 2 different ones (one USB3 and one USB2) but they didn't work. I have no idea why the HDD works but the flash drive doesn't. Tried in different ports. For the record my HDD is connected with USB2 because USB3 HDD interferes with Wi-Fi on 2.4GHz, haven't tried the HDD on the USB3 port. I also didn't have get LED's on  with mainline.

**Comment by whirm** [comment]
I've also have the same problem. I've got a:
 `ID 152d:0567 JMicron Technology Corp. / JMicron USA Technology Corp. JMS567 SATA 6Gb/s bridge`
And it won't be detected by any of the 5.* kernels i've tried (.1,.2,.3)
Works just fine with 4.4.XXX.

**Comment by svh1985** [comment]
Same issue here 😞Only USB2.0 works.

**Comment by ayufan** [comment]
This is supported as part of 0.10.x.
