### ISSUE TITLE
No more development for rock64?

### ISSUE THREAD

**Issue by gusarg81** [ayufan-rock64/linux-build#463]
I see there is no more pre-releases and releases as well.

Is the development abandoned?

**Comment by Username404-59** [comment]
I think so

**Comment by gusarg81** [comment]
What a shame, I will never use and not recommend Rockchip products like EVER...

Such a huge disappointment to have a useless SBC, nothing more than a paperweight.

**Comment by motla** [comment]
Hi @gusarg81, I guess if @ayufan has seen my issue he's seen your's as well.
First it's not ok to spam another issue to get attention on yours.
Second you may read the first lines of the README.md:
```
This is community maintained project in my free time. Don't expect everything to be perfect and working.
```
Also as a _"Software Libre lover"_ you should maybe also know that people behind free software do this on their free time and they are not paid for that. You don't pay them. As a result, you can't blame them.
Instead you will find a `Fork` button at the top right of every project on GitHub. It serves to copy the repository on your account giving you the opportunity to modify it and build it yourself. It may cost you a little time but you will learn a lot. 
And also you will give contribution to the community. It's how open-source works.

By the way there is a pre-release from a month ago:
https://github.com/ayufan-rock64/linux-build/releases/tag/0.11.0

What is your requirement to have the latest version anyway?

**Comment by gusarg81** [comment]
Hi @motla,

First of all, nobody is judging the project/code itself and am very ware that is a community driven repository.

As I said projects seems dead, is because @ayufan (or anyone part of this repo) seems to not even reply many issues that exist, and I guess that is why seems dead.

Secondly, as I said in another issue, none of the pre-releases boot in Rock64 v2.0 4GB (at least, in mine), only stable releases does (for example now I am using buster stable release but I need most of all to use Focal for my own projects/testing/development purposes).

And for the last, sorry for spamming issue over another issue.

**Comment by tcreek** [comment]
> What a shame, I will never use and not recommend Rockchip products like EVER...
> 
> Such a huge disappointment to have a useless SBC, nothing more than a paperweight.

This is not a RockChip issue, but a Pine64 issue. The expect the community to provide the software instead of them. Unlike Raspberry Pi where they offer the boards and software for competitive pricing.

If Pine64 offered more financial incentives, or provided some operating systems, I am sure they would be better off.
Let's take their SOEdge board for example. There is no OS available for it except which is provided by RockChip. It is very limited, and  no others distro developers are even interested in making anything for it.  So the SOEdge boards are sitting there in their inventory with nobody buying them.

**Comment by gusarg81** [comment]
So you were bored and you replied to this, which last message was from "Jun 7, 2021" :|

Anyways, I been using this SBC with Armbian. No easy hw accel yet, but well. I gave it another use (Like Home automation, backups system, etc.).

**Comment by tcreek** [comment]
No hardware acceleration because when Pine64 comes out with a new product, they tend to use older hardware and nobody wants to write drivers for older hardware. Their original Pine64 board was already abandoned by the distro makers about a year after its release. With their PinePhone which uses the original Pine64 board SOC, many distros were made for it, but no hardware driver development due to that old SOC the are using.

They also keep coming out with new stuff so development gets dropped for those older items. Seems their newer RockPro64 is more desired than the original Rock64

**Comment by steakknife** [comment]
Can't find a working OS for RockPro64. Everything for it is ancient, buggy, and useless.

**Comment by tcreek** [comment]
From the list on their wiki, none are functional?

https://wiki.pine64.org/wiki/ROCKPro64_Software_Releases
