### ISSUE TITLE
Whilst trying to build slic3r under stretch I hit a problem re libmali-rk-utgard-2th-r7p0_1.5ayufan12_arm64.deb

### ISSUE THREAD

**Issue by G4DCP** [ayufan-rock64/linux-build#50]
Can you advise me how to recover?

pdh@rock64:~/installs/Slic3r$ sudo apt --fix-broken install
Reading package lists... Done
Building dependency tree
Reading state information... Done
Correcting dependencies... Done
The following additional packages will be installed:
  libmali-rk-utgard-2th-r7p0
The following NEW packages will be installed:
  libmali-rk-utgard-2th-r7p0
0 upgraded, 1 newly installed, 0 to remove and 0 not upgraded.
51 not fully installed or removed.
Need to get 0 B/536 kB of archives.
After this operation, 1608 kB of additional disk space will be used.
Do you want to continue? [Y/n] y
(Reading database ... 248147 files and directories currently installed.)
Preparing to unpack .../libmali-rk-utgard-2th-r7p0_1.5-4ayufan12_arm64.deb ...
Unpacking libmali-rk-utgard-2th-r7p0:arm64 (1.5-4ayufan12) ...
Replacing files in old package libgbm1:arm64 (13.0.6-1+b2) ...
Replacing files in old package libgles2-mesa:arm64 (13.0.6-1+b2) ...
Replacing files in old package libegl1-mesa:arm64 (13.0.6-1+b2) ...
dpkg: error processing archive /var/cache/apt/archives/libmali-rk-utgard-2th-r7p0_1.5-4ayufan12_arm64.deb (--unpack):
 trying to overwrite '/usr/lib/aarch64-linux-gnu/libGLESv1_CM.so.1', which is also in package libgles1-mesa:arm64 13.0.6-1+b2
Errors were encountered while processing:
 /var/cache/apt/archives/libmali-rk-utgard-2th-r7p0_1.5-4ayufan12_arm64.deb
E: Sub-process /usr/bin/dpkg returned an error code (1)

**Comment by StuartIanNaylor** [comment]
http://opensource.rock-chips.com/wiki_Graphics

I have just been trying to get X11 to run with openGL ES 2.0 and glamor and installing libmali causes seg faults.
Rockchip have a custom xserver implementation but if you do an apt-cache showpkg [pkg] we are pulling xserver from the main debian distro's.

Maybe because it doesn't work :) I dunno but which version of stretch is that?
I am sort of confused as Rockchip seems to be concentrating on stretch whilst the supposed focus with the community builds is xenial.

http://opensource.rock-chips.com/wiki_Xserver
Branch rockchip-1.8
This branch is used for Rockchip Debian SDK, you could easily use it in your Debian. The current xserver version match the one in Debian stretch. But it would work fine with Debian Jessie if you enabled the Debian stretch repository and using x driver(likes fbdev) from it.

To say I am fair confused on what the xorg.conf should be and which modesettings we should have is an understatement.

Currently and apt-get upgrade and a reboot seems to kill my stretch-minimal-rock64-0.5.10-118-arm64

**Comment by xalius** [comment]
Latest pre-release images drop the custom X server...
